### ISSUE TITLE
Incorrect log data for Timeouts.

### ISSUE THREAD

**Issue by KaitheFoox** [PretendoNetwork/chubby#12] opened 2024-04-24 19:02 UTC
Issue: The bot's logs incorrectly mark the executor and the reason for a timeout when automod times a user out. The information put in its place seems to come from the last manual warning by a moderator.

How to replicate: It's now unknown how it's occuring; this could be an issue we have never noticed.

How to fix: I'm assuming it could be happening because Automod is not an account, so it's messing with the bot's method of grabbing the log information.

**Comment by wolfendale** [comment] 2024-07-15 21:35
I think #18 is a duplicate of this. We should close this in favour of #18 as it has more detail

**Comment by jonbarrow** [comment] 2024-07-20 19:01
> I think #18 is a duplicate of this. We should close this in favour of #18 as it has more detail

Getting to this kinda late, but I don't think it's a direct duplicate. #18 was about the incorrect names, this one was about incorrect times. While they may be caused by the same underlying problem they *are* reporting different issues

**Comment by wolfendale** [comment] 2024-07-20 19:09
This should also be fixed by #20 as the data for the event log comes directly from the audit log in this case

**Closed by wolfendale** 2024-07-20 19:09 UTC
